config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'pages#about'
  # verb 'path', to: 'controller#action'
  get 'contact', to: 'pages#contact'
  
  # if we want to create a path to the root, it's just '/'
  get '/', to: 'pages#home', as: :root
  # the above is the same as
  #  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    # hidden: render about.html.erb
  end

  def contact
    # this instance var is going to the view
    @team_mates = %w[Emanuele Maxim Gyorgyi Charles Hannah] 
    # hidden: render contact.html.erb

    if params[:member] # if it exists, we filter
      @team_mates = @team_mates.filter { |team_mate| team_mate == params[:member] }
    end
  end

  def home
    # hidden: render home.html.erb
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BananaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>BANANA APP</h1>
    <hr>

    <%= yield %>

    <hr>
    <p>Created with love in Batch 605 ❤</p>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hallo, Welt!</h1>

<p>We are a nice company. Hire us!</p>

<%= link_to 'Go back to Home', root_path %>

app/views/pages/contact.html.erb
<form action="/contact" method="get">
  <input type="text" 
         name="member" 
         placeholder="Who are you looking for?"
         value="<%= params[:member] %>"> 
  <input type="submit">
</form>

<ul>
  <%# this instance var is coming from the controller %>
  <% @team_mates.each do |team_mate| %>
    <li>
      <%= team_mate %>
    </li>
  <% end %>
</ul>

<%# print embedded - pe %>
<%# embedded ruby - er %>

<%= link_to 'Back to home', root_path %>

app/views/pages/home.html.erb
<h1>Welcome to my home page</h1>

<p>
  <% now = Time.now  %>
  The time now is <%= now %>
</p>

<p>
  1 + 2 = <%= 1 + 2 %>
</p>

<h2>LINKS</h2>
<a href="/contact">Contact Page</a>
<%= link_to 'Contact Page', '/contact' %>
<%= link_to 'Contact Page', contact_path %>

<%# <a href="/about">About</a> %>